### ISSUE TITLE
imgproxy_url helper is trying to modify passed options

### ISSUE THREAD

**Issue by sandrew** [imgproxy/imgproxy.rb#2]
Hi!
I'm using imgproxy gem with ActiveStorage. And when I pass a frozen hash as a processing options to the `imgproxy_url` helper, it raises an error:

```ruby
class Post
  IMAGE_DIMENSIONS = { width: 148, height: 96, resizing_type: :fill }.freeze
  has_one_attached :image
end

Post.find(666).image.imgproxy_url(Post::IMAGE_DIMENSIONS)
```

=> 

```
FrozenError (can't modify frozen Hash):
imgproxy (1.0.2) lib/imgproxy/builder.rb:23:in `delete'
imgproxy (1.0.2) lib/imgproxy/builder.rb:23:in `initialize'
imgproxy (1.0.2) lib/imgproxy.rb:73:in `new'
imgproxy (1.0.2) lib/imgproxy.rb:73:in `url_for'
imgproxy (1.0.2) lib/imgproxy/extensions/active_storage.rb:13:in `imgproxy_url'
```
That is caused by this line:
https://github.com/imgproxy/imgproxy.rb/blob/master/lib/imgproxy/builder.rb#L23

This is potentially harmful, as if somebody forgets to freeze the hash, it can lead to hardly catchable bugs.

**Comment by DarthSim** [comment]
Hi,

Sorry for delay and thanks for the report. Fixed in v1.0.3
