### ISSUE TITLE
Tag a new gem release for base64 configuration option

### ISSUE THREAD

**Issue by jrnk** [imgproxy/imgproxy.rb#45]
Is it possible to tag a new gem versions for the support added in https://github.com/imgproxy/imgproxy.rb/commit/541b0aaa7e730d94facf147faf04e6a142203485 ? 
We're using this in production and rather not tie it to a forked repo / master branch :)

Thanks!

**Comment by DarthSim** [comment]
Released in `1.2`

**Comment by jrnk** [comment]
Thanks @DarthSim !
